apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    type: back-end
    app: db
spec:
  containers:
    - name: db
      image: postgres:9.4
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 5432